# Generated by Django 5.1.7 on 2025-04-01 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewriteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_content", models.TextField(verbose_name="Nội dung gốc")),
                ("instructions", models.TextField(verbose_name="Hướng dẫn viết lại")),
                (
                    "rewritten_content",
                    models.TextField(blank=True, verbose_name="Nội dung đã viết lại"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu viết lại",
                "verbose_name_plural": "Các yêu cầu viết lại",
                "ordering": ["-created_at"],
            },
        ),
    ]
