# Generated by Django 5.1.7 on 2025-04-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rewriterequest",
            options={},
        ),
        migrations.AddField(
            model_name="rewriterequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="rewriterequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="rewriterequest",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rewriterequest",
            name="original_content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="rewriterequest",
            name="rewritten_content",
            field=models.TextField(blank=True),
        ),
    ]
