# Generated by Django 5.2 on 2025-04-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detection",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="detection",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detection",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="detection",
            name="translation_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
