# Generated by Django 5.2 on 2025-04-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0002_alter_detection_options_detection_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detection",
            name="translation_text",
        ),
    ]
