# Generated by Django 5.2 on 2025-04-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0003_remove_detection_translation_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detection",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="detection",
            name="title",
        ),
    ]
